parameters: {}
environment: {}
packages:
  - name: fffinkel
    environment: {}
    parameters: {}
    actions:
      - name: sensus-mwater-adapter
        main: ''
        runtime: 'go:1.20'
        environment: {}
        parameters: {}

