name: sensus-mwater-adapter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
          COVERAGE=$(cat coverage.out | grep total: | grep -Eo '[0-9]+\.[0-9]+')
          COVERAGE_INT=$(echo $COVERAGE | cut -d "." -f 1)
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "COVERAGE_COLOR=$([[ $COVERAGE_INT -ge 90 ]] && echo 'green' || echo 'red')" >> $GITHUB_ENV

      - name: Update Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: bb5d76c3d157a2497d578e1a30564c4a
          filename: coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}
          color: ${{ env.COVERAGE_COLOR }}
